# Generated by Django 5.2.5 on 2025-09-03 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0010_freightorder_freightorderline'),
    ]

    operations = [
        migrations.AddField(
            model_name='freightquotation',
            name='valid_until',
            field=models.DateField(blank=True, null=True),
        ),
    ]
