# Generated by Django 5.2.5 on 2025-09-06 22:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0011_freightquotation_valid_until'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TransportMode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ModeService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.serviceoption')),
                ('mode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.transportmode')),
            ],
            options={
                'unique_together': {('mode', 'service')},
            },
        ),
        migrations.CreateModel(
            name='LocationRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin_type', models.CharField(choices=[('CITY', 'City'), ('SEAPORT', 'Seaport'), ('AIRPORT', 'Airport')], max_length=20)),
                ('destination_type', models.CharField(choices=[('CITY', 'City'), ('SEAPORT', 'Seaport'), ('AIRPORT', 'Airport')], max_length=20)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.serviceoption')),
                ('mode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.transportmode')),
            ],
            options={
                'unique_together': {('mode', 'service')},
            },
        ),
    ]
