# Generated by Django 5.2.5 on 2025-09-07 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0012_businesstype_serviceoption_transportmode_modeservice_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentTerm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'payment_term',
                'ordering': ['code'],
            },
        ),
    ]
